// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneralRequest struct {
	Nonce                uint32   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Address2             string   `protobuf:"bytes,4,opt,name=address2,proto3" json:"address2,omitempty"`
	TransactionHash      []string `protobuf:"bytes,5,rep,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	GasLimit             uint64   `protobuf:"varint,6,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,7,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Payload              []byte   `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *GeneralRequest) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *GeneralRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GeneralRequest) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *GeneralRequest) GetTransactionHash() []string {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *GeneralRequest) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *GeneralRequest) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *GeneralRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralRequest)(nil), "transaction.GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "transaction.GeneralResponse")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xad, 0xdb, 0xba, 0xed, 0x4c, 0x37, 0x8c, 0x22, 0x61, 0x7a, 0x51, 0x76, 0x55, 0x10,
	0x76, 0x31, 0x1f, 0x41, 0x44, 0x11, 0x37, 0x24, 0x1b, 0xbb, 0x3f, 0x76, 0xc7, 0x1a, 0xe8, 0x92,
	0x99, 0xa4, 0xc8, 0x5e, 0xd5, 0xa7, 0xf0, 0x11, 0x64, 0xed, 0x5a, 0xab, 0x78, 0x57, 0xef, 0xf2,
	0x9d, 0x3f, 0xfc, 0xf9, 0xcf, 0x0f, 0x81, 0x13, 0x67, 0x50, 0x59, 0x8c, 0x9c, 0xd4, 0x6a, 0xbc,
	0x31, 0xda, 0x69, 0xd6, 0xab, 0x8c, 0x46, 0x9f, 0x1e, 0xf4, 0xef, 0x48, 0x91, 0xc1, 0x44, 0xd0,
	0x5b, 0x4a, 0xd6, 0xb1, 0x33, 0x68, 0x29, 0xad, 0x22, 0xe2, 0x5e, 0xe0, 0x85, 0xc7, 0x22, 0x07,
	0x76, 0x0e, 0x3e, 0xae, 0x75, 0xaa, 0x1c, 0x3f, 0x0c, 0xbc, 0xf0, 0x48, 0xec, 0x89, 0x71, 0x68,
	0xe3, 0x6a, 0x65, 0xc8, 0x5a, 0xde, 0x08, 0xbc, 0xb0, 0x2b, 0x0a, 0x64, 0x43, 0xe8, 0xec, 0x8f,
	0x13, 0xde, 0xcc, 0xa4, 0x92, 0x59, 0x08, 0x83, 0x4a, 0x8a, 0x7b, 0xb4, 0xaf, 0xbc, 0x15, 0x34,
	0xc2, 0xae, 0xf8, 0x3d, 0xde, 0xb9, 0xc4, 0x68, 0x1f, 0xe5, 0x5a, 0x3a, 0xee, 0x07, 0x5e, 0xd8,
	0x14, 0x25, 0xef, 0xb5, 0x27, 0x23, 0x23, 0xe2, 0xed, 0x2c, 0x55, 0xc9, 0xbb, 0x5c, 0x1b, 0xdc,
	0x26, 0x1a, 0x57, 0xbc, 0x93, 0x49, 0x05, 0x8e, 0xae, 0x60, 0x50, 0x6e, 0x6c, 0x37, 0x5a, 0xd9,
	0xec, 0xf2, 0x9a, 0xac, 0xc5, 0x38, 0x5f, 0xba, 0x2b, 0x0a, 0x9c, 0x7c, 0x34, 0xa0, 0xb7, 0xf8,
	0x8e, 0xc4, 0xa6, 0xd0, 0x9f, 0xd1, 0x7b, 0x75, 0x72, 0x31, 0xae, 0x56, 0xfc, 0xb3, 0xcb, 0xe1,
	0xe5, 0xdf, 0x62, 0xfe, 0xec, 0xe8, 0x80, 0x09, 0x38, 0xbd, 0xc1, 0x24, 0x4a, 0x13, 0x74, 0xb4,
	0xd0, 0x0e, 0x93, 0x25, 0x26, 0x29, 0xd5, 0xf3, 0x9c, 0xc1, 0x60, 0x2e, 0x63, 0xf5, 0x6f, 0x19,
	0x1f, 0xa0, 0xb7, 0xf3, 0x9b, 0xe6, 0x8d, 0xd4, 0xf3, 0xba, 0x05, 0x7f, 0x49, 0x46, 0xbe, 0x6c,
	0x6b, 0xdb, 0xcc, 0x9d, 0x91, 0x2a, 0xae, 0x65, 0xf3, 0xec, 0x67, 0x1f, 0xe2, 0xfa, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x5f, 0x80, 0x1e, 0x79, 0x25, 0x03, 0x00, 0x00,
}
