// Package crypto defines a set of helper methods for repetitive cryptographic operations used by the Polaris protocol.
package crypto

import (
	"encoding/hex"

	"lukechampine.com/blake3"
)

// Hash represents a 32-byte-long array generated by the blake3 hashing function.
type Hash [32]byte

// HashBlake3 hashes the given slice of data via the blake3 hashing algorithm.
func HashBlake3(b []byte) Hash {
	// Generate a hash of the given data via blake3, and coerce the resulting slice into a hash primitive
	return Hash(blake3.Sum256(b))
}

// String derives a string representation of the hash using base 16.
func (h *Hash) String() string {
	// Convert the slice of bytes into a string
	return hex.EncodeToString(h[:])
}
