// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto.proto

package crypto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneralRequest struct {
	PrivatePublicKey     string   `protobuf:"bytes,1,opt,name=privatePublicKey,proto3" json:"privatePublicKey,omitempty"`
	B                    []byte   `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	N                    float64  `protobuf:"fixed64,3,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{0}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}

func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}

func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}

func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}

func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetPrivatePublicKey() string {
	if m != nil {
		return m.PrivatePublicKey
	}
	return ""
}

func (m *GeneralRequest) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *GeneralRequest) GetN() float64 {
	if m != nil {
		return m.N
	}
	return 0
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{1}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}

func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}

func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}

func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}

func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralRequest)(nil), "crypto.GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "crypto.GeneralResponse")
}

func init() { proto.RegisterFile("crypto.proto", fileDescriptor_527278fb02d03321) }

var fileDescriptor_527278fb02d03321 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x22, 0xb8, 0xf8,
	0xdc, 0x53, 0xf3, 0x52, 0x8b, 0x12, 0x73, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xb4,
	0xb8, 0x04, 0x0a, 0x8a, 0x32, 0xcb, 0x12, 0x4b, 0x52, 0x03, 0x4a, 0x93, 0x72, 0x32, 0x93, 0xbd,
	0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x30, 0xc4, 0x85, 0x78, 0xb8, 0x18, 0x93,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x18, 0x93, 0x40, 0xbc, 0x3c, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0xc6, 0x20, 0xc6, 0x3c, 0x25, 0x6d, 0x2e, 0x7e, 0xb8, 0xc9, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x50, 0x13, 0x61, 0x5c,
	0xa3, 0x4b, 0x4c, 0x5c, 0x6c, 0xce, 0x60, 0x17, 0x09, 0x79, 0x71, 0x89, 0x3a, 0xa6, 0xa4, 0x14,
	0xa5, 0x16, 0x17, 0xbb, 0x15, 0xe5, 0xe7, 0x06, 0x40, 0xac, 0x04, 0x59, 0x26, 0xa6, 0x07, 0xf5,
	0x01, 0xaa, 0x83, 0xa5, 0xc4, 0x31, 0xc4, 0x21, 0xd6, 0x29, 0x31, 0x08, 0x79, 0x72, 0x89, 0x20,
	0x9b, 0x05, 0x77, 0x37, 0x19, 0x46, 0x59, 0x72, 0xb1, 0x04, 0x67, 0x24, 0x1a, 0x93, 0xa3, 0xd5,
	0x8a, 0x8b, 0x15, 0xa4, 0x35, 0x8f, 0x02, 0xbd, 0x29, 0x64, 0xe8, 0x4d, 0x62, 0x03, 0x47, 0xb5,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x8c, 0x85, 0xc6, 0xfa, 0x01, 0x00, 0x00,
}
